name: Print Tag on Release

on:
  release:
    types: [published]

jobs:
  print-release-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Print tag from release
        run: | 
          echo "📦 Release publicado com tag: ${{ github.event.release.tag_name }}"